[options]
addons_path = /odoo/addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$PEfIufcewziHsJYS4nzvvQ$eUpH7LrUZeCAuDJf.nQTiZYwanDO3vpwy7vRLqA5XuYmDg5rrGfGKnd3KuZnN6W6PrCulhAX9MS7Ceb.9Qtfuw
proxy_mode = False

